# Generated by Django 2.2 on 2019-04-25 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=datetime.date.today, verbose_name='D.O.B.'),
        ),
    ]
