# Generated by Django 3.0.1 on 2019-12-26 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191225_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
