# Generated by Django 3.0.1 on 2019-12-26 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_profile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created'),
        ),
    ]
