# Generated by Django 3.0.1 on 2019-12-26 18:52

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='Page Name')),
                ('site_url', models.CharField(max_length=250, verbose_name='URL')),
                ('site_category', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BLOG', 'Blog'), ('EDUCATION', 'Education'), ('ENTERTAINMENT', 'Entertainment'), ('NEWS', 'News'), ('MISCELLANEOUS', 'Miscellaneous'), ('SOCIAL', 'Social')], default=None, max_length=50, verbose_name='Category')),
                ('site_pinned_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Pinned')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=100, verbose_name='Link Name')),
                ('link_url', models.CharField(max_length=250, verbose_name='URL')),
                ('link_created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Link Created')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Posted')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
