# Generated by Django 3.0.7 on 2023-01-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230106_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=2, upload_to='uploads', verbose_name='Caption Image'),
            preserve_default=False,
        ),
    ]
