# Generated by Django 3.0.7 on 2023-01-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='preview_photos', verbose_name='Caption Image'),
        ),
    ]
