# Generated by Django 3.0.7 on 2023-01-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20230107_2355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PinnedSite',
        ),
    ]
